name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./ci/setup.sh
      - run: ./ci/build-and-test.sh
      - run: ./ci/format.sh --check
